language: node_js
node_js:
	- "4.1"
before_install:
	- npm install -g npm@3.9.5
	- npm prune
install:
	- npm install
script:
	- npm test
	- npm run check-coverage
branches:
	only:
		- master
cache:
	directories:
		- node_modules
notifications:
	email: false
