language: node_js
node_js:
  - "6.1"
before_install:
  - npm prune
script:
  - npm test
  - npm run coverage:check
after_success:
  - npm run coverage:report
  - npm run release
  - curl -sL https://sentry.io/get-cli/ | bash
  - npm run upload:maps
branches:
  only:
    - master
cache:
  directories:
    - node_modules
notifications:
  email: false
