language: node_js
node_js:
  - "6.1"
before_install:
  - npm prune
script:
  - npm test
  - npm run coverage:check
after_success:
  - npm run coverage:report
  - npm run release
cache:
  directories:
    - node_modules
notifications:
  email: false
